ethnicities = {
    'Other Asian': 'A',
    'Black': 'B',
    'Chinese': 'C',
    'Cambodian': 'D',
    'Filipino': 'F',
    'Guamanian': 'G',
    'Hispanic/Latin/Mexican': 'H',
    'American Indian/Alaskan Native': 'I',
    'Japanese': 'J',
    'Korean': 'K',
    'Laotian': 'L',
    'Other': 'O',
    'Pacific Islander': 'P',
    'Samoan': 'S',
    'Hawaiian': 'U',
    'Vietnamese': 'V',
    'White': 'W',
    'Unknown': 'X',
    'Asian Indian': 'Z',
}
